kind = "web"
previewPath = "/"
title = "XaFlow"
version = "1.0.0"
id = "artifacts/filmify"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24184

[services.development]
run = "pnpm --filter @workspace/filmify run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/filmify", "run", "build" ]
serve = "static"
publicDir = "artifacts/filmify/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24184"
BASE_PATH = "/"
